config/routes.rb
Rails.application.routes.draw do



  resources :posts
  resources :profiles
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :likes do 
	  member do
	    put "like", to: "likes#upvote"
	    put "dislike", to: "likes#downvote"
	  end
	end
  
  resources :admin
  
  resources :comments, only: [:create, :index, :destroy]

  get 'landing/index'
  get 'feed/index'
  get 'admin/index'
  get 'userprofile/index'
  get 'comments/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new
    can :manage, :all if user.role == 'admin' 
    can %i(edit delete), Post, :user_id => user.id
    can :delete if user.role == 'moderator'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  
  validates :body, presence: true, allow_blank: false
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user, optional: true
	mount_uploader :image, PostImgUploader
	has_one_attached :image
	has_many :comments, dependent: :destroy
	audited
	acts_as_votable

	validates :image, file_size: { less_than: 0.5.megabytes }
end

app/models/user.rb
class User < ApplicationRecord
  audited
  has_many :posts
  acts_as_voter
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :timeoutable, :lockable
         protected
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!
	def index
		@users = User.all
	end

	def show

	end

	def update  
		@user = User.find(params[:id])

	    @user.role = @user.role == 'moderator' ? 'user' : 'moderator'
	    if @user.save
	      flash[:success] = "Status updated successfully!"
	      redirect_to admin_index_path
	    else
	    	
	  	end
	end

	def select
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :set_user, except: :front
  # respond_to :html, :js

  def index
    # issuer = 'Memeconomy'
    # label = "#{issuer}:#{current_user.email}"

    # current_user.otp_provisioning_uri(label, issuer: issuer)

    # # > "otpauth://totp/Your%20App:user@example.com?secret=[otp_secret]&issuer=Your+App"

    current_user.otp_secret = User.generate_otp_secret
    current_user.otp_required_for_login = true
    current_user.save!

    @qr = RQRCode::QRCode.new(current_user.otp_provisioning_uri(current_user.email, secret: current_user.otp_secret, issuer: "Devise-Two-Factor-Demo"))
    
    # With default options specified explicitly
    @svg = @qr.as_svg(offset: 10, module_size: 7)

  end

  # def front
  #   @activities = PublicActivity::Activity.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  # end

  # def find_friends
  #   @friends = @user.all_following
  #   @users =  User.where.not(id: @friends.unshift(@user)).paginate(page: params[:page])
  # end

  # private
  # def set_user
  #   @user = current_user
  # end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # def new
  # end

  # def show
  # end

  # def update
  # end

  # def destroy
  # end

  def upvote 
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to posts_path
  end  

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!
  def new
  	@post = Post.new
    @comment = Comment.new
  end

  def update
    @post = Post.find(params[:id])
    @post.description = permit_post_update[:description]
    @post.category = permit_post_update[:category]
    if @post.save
      flash[:error] = "Post updated successfully!"
      redirect_to post_path(@post)
    else
      flash[:error] = "Could not update meme :/ Please try again."
      redirect_to new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end     

  def index
  	@posts = Post.all
    @posts = @posts.order('created_at DESC')
    @comment = Comment.new
    @comments = Comment.all
  end

  def show
  	@post = Post.find(params[:id])
  end	

  def create
  	@post = Post.new(permit_post)
  	if @post.save
  		flash[:success] = "Success! New post created."
  		redirect_to post_path(@post)
    else
  		flash[:error] = "Could not create meme :/ Please try again."
  		redirect_to new_post_path
  	end
    
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = "Post successfully deleted."
      redirect_to posts_path
    else
      flash[:error] = "Could not delete meme :/ Please try again."
      redirect_to post_path(@post)
    end
  end

  private
  	def permit_post
  		params.require(:post).permit(:image, :description, :category, :user_id)
  	end

  private
    def permit_post_update
      params.require(:post).permit(:description, :category)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def enable_otp
    current_user.otp_secret = User.generate_otp_secret
    current_user.otp_required_for_login = true
    current_user.save!
    redirect_to home_index_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/userprofile_helper.rb
module UserprofileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="jumbotron">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Moderator</th>
        <th scope="col">Mod/Unmod</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |u| %>
       <% if u.role != 'admin' %>
        <tr class="table-info">
          <th scope="row"><%= u.email %></th>
          <td><%= u.role %></td>
          <td><%= link_to "Update Status" , admin_path(u), method: :patch, data: {confirm: "Are you sure?"} %></td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ssd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <% begin %>
      <%= stylesheet_link_tag params[:controller] %>
    <% rescue %>
    <% end %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary" role="navigation">
      <a class="navbar-brand" href="/">Memeconomy</a>
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item <%= 'active' if (params[:controller] == 'posts' && params[:action] == 'index') %>"> <a href="/posts" class="nav-link"> Browse </a></li>
          <% if current_user.role != 'admin' %>
            <li class="nav-item <%= 'active' if params[:controller] == 'posts' && params[:action] == 'new' %>"> 
              <%= link_to "New Meme", new_post_path, class: "nav-link" %> 
            </li>
            <% else %>
              <li>
              <%= link_to "Admin", admin_index_path, class:"nav-link" %>
              </li>
          <% end %>
          
        <% else %>
          <li class="nav-item <%= 'active' if params[:controller] == 'devise/sessions' && params[:action] == 'new' %>"> <a href="/users/sign_in" class="nav-link"> Sign In </a></li>
          <li class="nav-item <%= 'active' if params[:controller] == 'devise/registrations' && params[:action] == 'new' %>"> <a href="/users/sign_up" class="nav-link"> Sign Up </a></li>
        <% end %>
      </ul>
      <ul style="float: right;" class="nav navbar-nav navbar-right">
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, method: :get, class: "nav-link" %>        
          <% else %>
          <% end %>
        </li>
      </ul>
    </nav>

    <!-- uses bootstrap to produce a message of your choice -->
    <% flash.each do |a, b| %> 
      <div class="alert alert-success"> <%= b %> </div>
    <% end %>

    <div class="row">

    <%= yield %>

</div>
  </body>
</html>

app/views/public_activity/event/_create.html.erb
<div id="event-<%= activity.trackable.id %>" class="activity-event">
  <%= render activity.trackable, remote: true %>
</div>

app/views/public_activity/event/_like.html.erb
<% if activity.trackable %>
  <div class="activity-like">
    <div class="info">
      <%= render 'shared/avatar', user: activity.owner %>
      <h4 class="name"><%= link_to activity.owner.name, user_path(activity.owner) %></h4>
      <span class="action">liked a <%= link_to 'event', activity.trackable %></span>
    </div>
    <div class="content">
      <h4><small><%= activity.trackable.name %></small></h4>
      <h4><small><%= fa_icon'calendar' %> <%= formatted_time(activity.trackable.when) %></small></h4>
    </div>
    <%= render 'shared/created_at', activity: activity %>
  </div>
<% end %>