config/routes.rb
Rails.application.routes.draw do



  resources :posts
  resources :profiles
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :likes do 
	  member do
	    put "like", to: "likes#upvote"
	    put "dislike", to: "likes#downvote"
	  end
	end
  
  resources :admin
  
  resources :comments, only: [:create, :index, :destroy]

  get 'landing/index'
  get 'feed/index'
  get 'admin/index'
  get 'userprofile/index'
  get 'comments/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new
    can :manage, :all if user.role == 'admin' 
    can %i(edit delete), Post, :user_id => user.id
    can :delete if user.role == 'moderator'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  
  validates :body, presence: true, allow_blank: false
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user, optional: true
	mount_uploader :image, PostImgUploader
	has_one_attached :image
	has_many :comments, dependent: :destroy
	audited
	acts_as_votable

	validates :image, file_size: { less_than: 0.5.megabytes }
end

app/models/user.rb
class User < ApplicationRecord
  audited
  has_many :posts
  acts_as_voter
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :timeoutable, :lockable
         protected
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!
	def index
		@users = User.all
	end

	def show

	end

	def update  
		@user = User.find(params[:id])

	    @user.role = @user.role == 'moderator' ? 'user' : 'moderator'
	    if @user.save
	      flash[:success] = "Status updated successfully!"
	      redirect_to admin_index_path
	    else
	    	
	  	end
	end

	def select
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, except:[:index]


	def comment_params
		params.require(:comment).permit(:body)
	end

	def index
		@post = Post.find(params[:comment][:post_id])
		@comments = @post.comments.order(created_at: :desc)
	end

	def create
		@post = Post.find(params[:comment][:post_id])
		@comment = Comment.new
		@comment = @post.comments.new(comment_params)
		@comment.user = current_user

		if @comment.save
			flash[:success] = "Comment added!"
			redirect_to post_path(@post)
		end
	end

	def destroy
		@post = Post.find(params[:comment][:post_id])
		@comment = @post.comments.find(params[:comment][:comment_id])
		@user = @comment.user.id

		if (@user == current_user.id || current_user.role == 'moderator')
			@comment.destroy
			if @comment.destroy
				flash[:success] = "Comment deleted!"
				redirect_to posts_path
			end
		else
			flash[:error] = "this comment is not yours"
			redirect_to posts_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :set_user, except: :front
  # respond_to :html, :js

  def index
    # issuer = 'Memeconomy'
    # label = "#{issuer}:#{current_user.email}"

    # current_user.otp_provisioning_uri(label, issuer: issuer)

    # # > "otpauth://totp/Your%20App:user@example.com?secret=[otp_secret]&issuer=Your+App"

    current_user.otp_secret = User.generate_otp_secret
    current_user.otp_required_for_login = true
    current_user.save!

    @qr = RQRCode::QRCode.new(current_user.otp_provisioning_uri(current_user.email, secret: current_user.otp_secret, issuer: "Devise-Two-Factor-Demo"))
    
    # With default options specified explicitly
    @svg = @qr.as_svg(offset: 10, module_size: 7)

  end

  # def front
  #   @activities = PublicActivity::Activity.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  # end

  # def find_friends
  #   @friends = @user.all_following
  #   @users =  User.where.not(id: @friends.unshift(@user)).paginate(page: params[:page])
  # end

  # private
  # def set_user
  #   @user = current_user
  # end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
    def index
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # def new
  # end

  # def show
  # end

  # def update
  # end

  # def destroy
  # end

  def upvote 
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to posts_path
  end  

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to posts_path
  end
end

app/controllers/moderator_controller.rb
class ModeratorController < ApplicationController
	before_action :authenticate_user!
	def index
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!
  def new
  	@post = Post.new
    @comment = Comment.new
  end

  def update
    @post = Post.find(params[:id])
    @post.description = permit_post_update[:description]
    @post.category = permit_post_update[:category]
    if @post.save
      flash[:error] = "Post updated successfully!"
      redirect_to post_path(@post)
    else
      flash[:error] = "Could not update meme :/ Please try again."
      redirect_to new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end     

  def index
  	@posts = Post.all
    @posts = @posts.order('created_at DESC')
    @comment = Comment.new
    @comments = Comment.all
  end

  def show
  	@post = Post.find(params[:id])
  end	

  def create
  	@post = Post.new(permit_post)
  	if @post.save
  		flash[:success] = "Success! New post created."
  		redirect_to post_path(@post)
    else
  		flash[:error] = "Could not create meme :/ Please try again."
  		redirect_to new_post_path
  	end
    
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = "Post successfully deleted."
      redirect_to posts_path
    else
      flash[:error] = "Could not delete meme :/ Please try again."
      redirect_to post_path(@post)
    end
  end

  private
  	def permit_post
  		params.require(:post).permit(:image, :description, :category, :user_id)
  	end

  private
    def permit_post_update
      params.require(:post).permit(:description, :category)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def enable_otp
    current_user.otp_secret = User.generate_otp_secret
    current_user.otp_required_for_login = true
    current_user.save!
    redirect_to home_index_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/userprofile_helper.rb
module UserprofileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<h1 class="heading">Update Meme</h1>

<div class="container">
	<%= form_for @post, html: { multipart: true } do |f| %>
		<%= image_tag @post.image.url %>

		<div class="form-group py-3">
			<%= f.label :description %>
			<%= f.text_area :description, class: "form-control" %>
		</div>

		<div class="form-group py-3">
			<%= f.label :category %>
			<%= select_tag(:category, options_for_select([["Animals", "Animals"], ["Art", "Art"], ["Futuristic", "Futuristic"], ["Politics", "Politics"], ["Vintage", "Vintage"]])) %>
		</div>

		<%= f.hidden_field :user_id, :value => current_user.id %>

		<%= f.submit class: "btn btn-primary" %> 
	<% end %>
</div>

app/views/posts/index.html.erb
<h1 class="heading">All Memes</h1>

<div class="container col-10 p-0">
	<% @posts.each do |x| %>
		<div class="card border-primary mb-3 mx-1">
		  	<div class="card-header">
		  		<span> by <span class="blue"><%= x.user.name %></span> 
		  		<br>on <%= x.created_at.strftime("%d %B %l:%M %p") %>
		  		<% if current_user.voted_for? x %>
	  				<%= link_to dislike_like_path(x), method: :put, class: "float-right like" do %>
			  			<i class="fas fa-heart"></i>
	  					<%= x.get_upvotes.size %>
					<% end %>
	  			<% else %>
	  				<%= link_to like_like_path(x), method: :put, class: "float-right like" do %>
			  			<i class="far fa-heart"></i> 	
	  					<%= x.get_upvotes.size %>
					<% end %>
				<% end %>

		  		</span>
		  	

				<% if x.user_id == current_user.id %>
				<div class="float-right">
				<% if can? :edit, x %>
					<%= link_to "Edit Post", edit_post_path(x) %>
					<% end %>
					|
					<% if can? :delete, x %>
					<%= link_to "Delete Post", post_path(x), method: :delete, data: {confirm: "Are you sure?"}, class: "float-right" %>
					<% end %>
				</div>
				<% end %>
		  	</div>
		  	<div class="card-body">
		  		<div class="card-img">
		  			<%= link_to image_tag(x.image), post_path(:id => x.id) %>
		  		</div>
		    	<p class="card-text">
		    		<span class="description"> <%= x.description %> </span>

		    		<div class="list-group">
		    			<% @comments.each do |c| %>
		    				<a class="list-group-item">
		    					<%= form_for @comment, url: comment_path(c), method: :delete do |f| %>
		    						<%= f.hidden_field :comment_id, :value => c.id %>
		    						<%= f.hidden_field :post_id, :value => x.id %>
		    						<%= f.submit class: "btn btn-outline-secondary btn-sm float-right" %>
		    					<% end %>
		    				<span><%= c.user.name %></span>
		    				<br>
		    				<%= c.body %></a>
		    			<% end %>
		    		</div>
				</p>
				<p class="card-text font-italic category">
					Category: <%= x.category %>
				</p>
					
				<div class="card-footer">
				<%= form_for @comment do |f| %>
					<%= f.text_field :body, class: "form-control mb-2" %>
					<%= f.hidden_field :post_id, :value => x.id %>

					<%= f.submit class: "btn btn-outline-secondary btn-sm float-right" %>
					<br />
				<% end %>
				<% if can? :manage, x %>
					<%= link_to "Delete Post", post_path(x), method: :delete, data: {confirm: "Are you sure?"}, class: "float-right" %>
					<% end %>
				</div>
		  	</div>
		</div>
	<% end %>
</div>

app/views/posts/new.html.erb
<h1 class="heading">New Meme</h1>

<div class="container">
	<%= form_for @post, html: { multipart: true } do |f| %>
		<div class="form-group">
			<%= f.label :image %>
			<%= f.file_field :image, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :description %>
			<%= f.text_area :description, class: "form-control" %>
		</div>

		<div class=form-group">
			<%= f.label :category %>
			<%= f.select(:category, ["Animals", "Art", "Futuristic", "Political", "Vintage"]) %>
		</div>

		<%= f.hidden_field :user_id, :value => current_user.id %>

		<%= f.submit class: "btn btn-primary mt-2" %> 
	<% end %>
</div>

app/views/posts/show.html.erb
<h1 class="heading">M3me</h1>

<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this pet from being saved:</h2>
 
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container show">
	<div class="card border-primary mb-3">
		  	<div class="card-header">
		  		<span> by <span class="blue"><%= @post.user.name %></span> </span>
		  		<br>
				<span> on <%= @post.created_at.strftime("%d %B %l:%M %p") %></span>
		  	</div>
		  	<div class="card-body">
		  		<div class="card-img">
		  			<%= image_tag @post.image %>
		  		</div>
		    	<p class="card-text">
		    		<span class="description"> <%= @post.description %> </span>
				</p>
				<p class="card-text font-italic category">
					Category: <%= @post.category %>
				</p>
				<% if can? :manage, @post %>
					<div class="card-footer">
						<%= link_to "Edit Post", edit_post_path(@post) %>
						<%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "float-right" %>
					</div>
				<% end %>
		  	</div>
		</div>
</div>

app/views/public_activity/post/_create.html.erb
<div id="post-<%= activity.trackable.id %>" class="activity-post">
  <%= render activity.trackable, remote: true %>
</div>

app/views/public_activity/post/_like.html.erb
<% if activity.trackable %>
  <div class="activity-like">
    <div class="info">
      <%= render 'shared/avatar', user: activity.owner %>
      <h4 class="name"><%= link_to activity.owner.name, user_path(activity.owner) %></h4>
      <span class="action">liked a <%= link_to 'post', activity.trackable %></span>
    </div>
    <div class="content">
      <h4><small><%= activity.trackable.content %></small></h4>
    </div>
    <%= render 'shared/created_at', activity: activity %>
  </div>
<% end %>